Repository Space2Study-UA-1125/frontEnd, pull requests merged in 2024-03, with the labels that each got.

#228 Bugfix/223/popup window is showing twice on the loginsignup form
  src/components/user-steps-wrapper/UserStepsWrapper.jsx
  src/containers/guest-home-page/signup-dialog/SignupDialog.jsx
  src/context/modal-context.jsx
Labels: bug, Sign up, Stepper, sprint 5

#244 Bugfix/231/stepper the content in the stepper has the different width
  src/components/user-steps-wrapper/UserStepsWrapper.jsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.jsx
  src/containers/tutor-home-page/add-photo-step/AddPhotoStep.styles.js
  src/containers/tutor-home-page/basestyles.styles.js
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
  src/containers/tutor-home-page/general-info-step/GeneralInfoStep.styles.js
  src/containers/tutor-home-page/language-step/LanguageStep.jsx
  src/containers/tutor-home-page/language-step/LanguageStep.styles.js
  src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx
  src/containers/tutor-home-page/subjects-step/SubjectsStep.styles.js
  tests/unit/containers/tutor-home-page/add-photo-step/AddPhotoStep.spec.jsx
  tests/unit/containers/tutor-home-page/general-info-step/GeneralInfoStep.spec.jsx
  tests/unit/containers/tutor-home-page/subjects-step/SubjectsStep.spec.jsx
Labels: bug, Stepper

#246 Feature/175/sp 1 find offers implement popular categories block
  src/components/popular-categories/PopularCategories.jsx
  src/components/popular-categories/PopularCategories.style.js
  tests/unit/components/popular-categories/PopularCategories.spec.jsx
Labels: feature, FrontEnd part, Find offers, sprint 6
